# acpd -- Archive issue, git add -u, Commit, Push, Deploy (dev only).
#
# Usage:
#   deploy.ps1 <issue-number> <commit-summary...>   # process one issue, no prompts
#   deploy.ps1 --pending                             # list issue numbers ready to deploy
#
# Native PowerShell port of deploy.sh, for hosts without bash/WSL. Same
# steps, same guarantees (fails before any git mutation, never touches
# qa/prod, only ever --env dev). See deploy.sh for the canonical,
# most-exercised implementation and full commentary; this file mirrors it.
#
# NOTE ON NAMING: this script is also called `deploy.ps1`, and step 7 below
# calls a DIFFERENT `deploy.ps1` -- the target repo's own per-environment
# deploy entry point (generated in step 3 if the repo doesn't have one yet).
# They live in different places: this one is
# `.claude/skills/acpd/deploy.ps1` (invoked explicitly, from the skill
# dir); the other is `<target-repo>/deploy.ps1` (what step 7 runs as
# `.\deploy.ps1 --env dev`, relative to the target repo root).

$ErrorActionPreference = "Stop"

function Show-Usage {
    Write-Host "Usage: deploy.ps1 <issue-number> <commit-summary...>"
    Write-Host "       deploy.ps1 --pending"
    exit 1
}

if ($args.Count -lt 1) { Show-Usage }

$RepoRoot = (git rev-parse --show-toplevel).Trim()
Set-Location $RepoRoot

# --pending: an issue is "pending deploy" once tdd2 has filled in its
# `## 구현 결과` section (구현 완료 일시 is no longer the "(미정)" placeholder)
# but the issue file hasn't been archived yet. No separate state file --
# this reuses the issue template's own completion marker.
if ($args[0] -eq "--pending") {
    Get-ChildItem -Path "issues" -Filter "issue-*.md" -File -ErrorAction SilentlyContinue | ForEach-Object {
        $content = Get-Content $_.FullName -Raw
        if ($content -match '\*\*구현 완료 일시\*\*:' -and $content -notmatch '\*\*구현 완료 일시\*\*:\s*\(미정\)') {
            $_.BaseName -replace '^issue-', ''
        }
    }
    exit 0
}

if ($args.Count -lt 2) { Show-Usage }
$IssueNum = $args[0]
$Summary = ($args[1..($args.Count - 1)] -join ' ')

$IssueFile = "issues/issue-$IssueNum.md"
if (-not (Test-Path $IssueFile -PathType Leaf)) {
    Write-Host "ERROR: $IssueFile not found"
    exit 1
}

# 0. Python-project verification gate. Detected via pyproject.toml at the
# repo root. For each check, prefer the project's own .\run-<name>.ps1 if
# it exists; otherwise fall back to this skill's bundled default in
# defaults\ (never copied into the project -- see SKILL.md). Runs before
# any git mutation, so a failure here leaves the repo untouched.
$SkillDir = Split-Path -Parent $PSCommandPath
$DefaultsDir = Join-Path $SkillDir "defaults"

function Invoke-Check {
    param([string]$Name)
    $projectScript = ".\$Name.ps1"
    if (Test-Path $projectScript -PathType Leaf) {
        Write-Host "--- $Name (project script) ---"
        & $projectScript
    } else {
        Write-Host "--- $Name (acpd default) ---"
        & (Join-Path $DefaultsDir "$Name.ps1")
    }
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: $Name failed (exit $LASTEXITCODE)"
        exit $LASTEXITCODE
    }
}

if (Test-Path "pyproject.toml" -PathType Leaf) {
    Write-Host "Python project detected (pyproject.toml) -- running verification gate before merge..."
    foreach ($chk in @("run-ruff", "run-pyright", "run-unit-tests", "run-regression-tests", "run-pyright-full")) {
        Invoke-Check $chk
    }
}

# 1. Stage the issue file's own changes (e.g. the "구현 결과" section).
git add $IssueFile

# 2. Archive: move to issues/archive/YYYY/MM/DD/ (git mv auto-stages the rename).
$ArchiveDir = "issues/archive/$(Get-Date -Format 'yyyy/MM/dd')"
New-Item -ItemType Directory -Force -Path $ArchiveDir | Out-Null
git mv $IssueFile "$ArchiveDir/issue-$IssueNum.md"

# 3. Ensure the TARGET REPO's own deploy entry points exist: deploy.ps1 (the
# one step 7 below calls), plus deploy.sh / deploy.bat for other hosts.
# Each is generated independently, only if missing, as a thin dispatcher
# that prefers a legacy deploy-to-<env>.{sh,bat,ps1} when present, and
# otherwise stubs out with a TODO. Committed alongside the archive so
# future acpd runs (or a human on another platform) have a real target.
if (-not (Test-Path "deploy.ps1" -PathType Leaf)) {
    @'
# Auto-generated by the acpd skill -- generic deploy entry point for this
# project. Dispatches to a legacy .\deploy-to-<env>.ps1 if this project
# already has one; otherwise this is a TODO stub. Replace with real deploy
# steps. (Not to be confused with acpd's own deploy.ps1, which is what
# generated this file.)
param(
    [string]$Env = "dev"
)

$legacy = ".\deploy-to-$Env.ps1"
if (Test-Path $legacy) {
    & $legacy
    exit $LASTEXITCODE
}

Write-Warning "TODO: this project's deploy.ps1 has no implementation for --env $Env yet."
Write-Warning "Add real deploy steps here (or add $legacy), then re-run acpd."
exit 0
'@ | Set-Content -Path "deploy.ps1" -Encoding utf8
    git add "deploy.ps1"
    Write-Host "NOTE: this project has no deploy.ps1 -- created a placeholder/dispatcher and staged it."
}

if (-not (Test-Path "deploy.sh" -PathType Leaf)) {
    $deploySh = "#!/usr/bin/env bash`n" +
        "# Auto-generated by the acpd skill -- generic deploy entry point for this`n" +
        "# project. Dispatches to a legacy ./deploy-to-<env>.sh if this project`n" +
        "# already has one; otherwise this is a TODO stub. Replace with real deploy`n" +
        "# steps.`n" +
        "set -euo pipefail`n`n" +
        "ENV=`"dev`"`n" +
        "while [ `$# -gt 0 ]; do`n" +
        "  case `"`$1`" in`n" +
        "    --env) ENV=`"`$2`"; shift 2 ;;`n" +
        "    *) shift ;;`n" +
        "  esac`n" +
        "done`n`n" +
        "LEGACY=`"./deploy-to-`${ENV}.sh`"`n" +
        "if [ -x `"`$LEGACY`" ]; then`n" +
        "  exec `"`$LEGACY`"`n" +
        "fi`n`n" +
        "echo `"TODO: this project's deploy.sh has no implementation for --env `$ENV yet.`" >&2`n" +
        "echo `"Add real deploy steps here (or add `$LEGACY), then re-run acpd.`" >&2`n" +
        "exit 0`n"
    Set-Content -Path "deploy.sh" -Value $deploySh -Encoding utf8 -NoNewline
    git add "deploy.sh"
    Write-Host "NOTE: this project has no deploy.sh -- created a placeholder/dispatcher and staged it."
}

if (-not (Test-Path "deploy.bat" -PathType Leaf)) {
    @'
@echo off
setlocal
rem Auto-generated by the acpd skill -- generic deploy entry point for this
rem project. Dispatches to a legacy deploy-to-<env>.bat if this project
rem already has one; otherwise this is a TODO stub. Replace with real
rem deploy steps.
set ENV=dev

:parse
if "%~1"=="" goto after
if /I "%~1"=="--env" (
    set ENV=%~2
    shift
    shift
    goto parse
)
shift
goto parse
:after

if exist "deploy-to-%ENV%.bat" (
    call "deploy-to-%ENV%.bat"
    exit /b %ERRORLEVEL%
)

echo TODO: this project's deploy.bat has no implementation for --env %ENV% yet. 1>&2
echo Add real deploy steps here (or add deploy-to-%ENV%.bat), then re-run acpd. 1>&2
exit /b 0
'@ | Set-Content -Path "deploy.bat" -Encoding ascii
    git add "deploy.bat"
    Write-Host "NOTE: this project has no deploy.bat -- created a placeholder/dispatcher and staged it."
}

# 4. Stage the rest of the already-tracked changes (never untracked files).
git add -u

# 5. Commit code + archiving as ONE commit.
$CommitMsg = "issue-${IssueNum}: $Summary`n`nCo-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>"
git commit -m $CommitMsg

# 6. Push.
git push

# 7. Deploy -- dev only, ever. Calls the TARGET REPO's own deploy.ps1 (see
# step 3), not this script.
& ".\deploy.ps1" --env dev
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

Write-Host "✓ acpd complete: issue-$IssueNum archived to $ArchiveDir/, committed, pushed, this project's deploy.ps1 --env dev run."
