#!/usr/bin/env bash
# acpd — Archive issue, git add -u, Commit, Push, Deploy (dev only).
#
# Usage:
#   deploy.sh <issue-number> <commit-summary...>   # process one issue, no prompts
#   deploy.sh --pending                             # list issue numbers ready to deploy
#
# NOTE ON NAMING: this script is also called `deploy.sh`, and step 7 below
# calls a DIFFERENT `deploy.sh` — the target repo's own per-environment
# deploy entry point (generated in step 3 if the repo doesn't have one yet).
# They live in different places: this one is
# `.claude/skills/acpd/deploy.sh` (invoked explicitly, from the skill dir);
# the other is `<target-repo>/deploy.sh` (the thing step 7 runs as
# `./deploy.sh --env dev`, relative to the target repo root). Throughout
# this file "this script" / "the acpd script" always means the former.
#
# Preconditions: run from inside the target repo (any subdirectory). Code
# changes for the issue must already be `git add`ed — that's the hand-off
# point from /tdd2.
#
# Never touches qa/prod. Only ever deploys --env dev.
set -euo pipefail

usage() {
  echo "Usage: deploy.sh <issue-number> <commit-summary...>" >&2
  echo "       deploy.sh --pending" >&2
  exit 1
}

[ $# -ge 1 ] || usage

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

# --pending: an issue is "pending deploy" once tdd2 has filled in its
# `## 구현 결과` section (구현 완료 일시 is no longer the "(미정)" placeholder)
# but the issue file hasn't been archived yet. No separate state file —
# this reuses the issue template's own completion marker.
if [ "${1:-}" = "--pending" ]; then
  shopt -s nullglob
  for f in issues/issue-*.md; do
    if grep -q '\*\*구현 완료 일시\*\*:' "$f" \
       && ! grep -q '\*\*구현 완료 일시\*\*: *(미정)' "$f"; then
      basename "$f" .md | sed 's/^issue-//'
    fi
  done
  exit 0
fi

[ $# -ge 2 ] || usage
ISSUE_NUM="$1"
shift
SUMMARY="$*"

ISSUE_FILE="issues/issue-${ISSUE_NUM}.md"
if [ ! -f "$ISSUE_FILE" ]; then
  echo "ERROR: $ISSUE_FILE not found" >&2
  exit 1
fi

# 0. Python-project verification gate. Detected via pyproject.toml at the
# repo root. For each check, prefer the project's own ./run-<name>.sh if it
# exists (and is executable); otherwise fall back to this skill's bundled
# default in defaults/ (never copied into the project — see SKILL.md).
# Runs before any git mutation, so a failure here leaves the repo untouched.
SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULTS_DIR="$SKILL_DIR/defaults"

run_check() {
  local name="$1"
  if [ -x "./${name}.sh" ]; then
    echo "--- ${name} (project script) ---"
    "./${name}.sh"
  else
    echo "--- ${name} (acpd default) ---"
    bash "$DEFAULTS_DIR/${name}.sh"
  fi
}

if [ -f pyproject.toml ]; then
  echo "Python project detected (pyproject.toml) — running verification gate before merge..."
  for chk in run-ruff run-pyright run-unit-tests run-regression-tests run-pyright-full; do
    run_check "$chk"
  done
fi

# 1. Stage the issue file's own changes (e.g. the "구현 결과" section).
git add "$ISSUE_FILE"

# 2. Archive: move to issues/archive/YYYY/MM/DD/ (git mv auto-stages the rename).
ARCHIVE_DIR="issues/archive/$(date +%Y/%m/%d)"
mkdir -p "$ARCHIVE_DIR"
git mv "$ISSUE_FILE" "$ARCHIVE_DIR/issue-${ISSUE_NUM}.md"

# 3. Ensure the TARGET REPO's own deploy entry points exist: deploy.sh (the
# one step 7 below calls), plus deploy.bat / deploy.ps1 for Windows targets
# — several of these projects deploy to Windows boxes over ssh (see e.g.
# deploy-to-dev.sh in smarthome-project, which shells out to a .bat on the
# remote host). Each is generated independently, only if missing, as a thin
# dispatcher that prefers a legacy deploy-to-<env>.{sh,bat,ps1} when present,
# and otherwise stubs out with a TODO. Committed alongside the archive so
# future acpd runs (or a human on Windows) have a real target.
if [ ! -f deploy.sh ]; then
  cat > deploy.sh <<'EOF'
#!/usr/bin/env bash
# Auto-generated by the acpd skill — generic deploy entry point for this
# project. Dispatches to a legacy ./deploy-to-<env>.sh if this project
# already has one; otherwise this is a TODO stub. Replace with real deploy
# steps. (Not to be confused with acpd's own deploy.sh, which is what
# generated this file.)
set -euo pipefail

ENV="dev"
while [ $# -gt 0 ]; do
  case "$1" in
    --env) ENV="$2"; shift 2 ;;
    *) shift ;;
  esac
done

LEGACY="./deploy-to-${ENV}.sh"
if [ -x "$LEGACY" ]; then
  exec "$LEGACY"
fi

echo "TODO: this project's deploy.sh has no implementation for --env $ENV yet." >&2
echo "Add real deploy steps here (or add $LEGACY), then re-run acpd." >&2
exit 0
EOF
  chmod +x deploy.sh
  git add deploy.sh
  echo "NOTE: this project has no deploy.sh — created a placeholder/dispatcher and staged it." >&2
fi

if [ ! -f deploy.bat ]; then
  cat > deploy.bat <<'EOF'
@echo off
setlocal
rem Auto-generated by the acpd skill -- generic deploy entry point for this
rem project. Dispatches to a legacy deploy-to-<env>.bat if this project
rem already has one; otherwise this is a TODO stub. Replace with real
rem deploy steps.
set ENV=dev

:parse
if "%~1"=="" goto after
if /I "%~1"=="--env" (
    set ENV=%~2
    shift
    shift
    goto parse
)
shift
goto parse
:after

if exist "deploy-to-%ENV%.bat" (
    call "deploy-to-%ENV%.bat"
    exit /b %ERRORLEVEL%
)

echo TODO: this project's deploy.bat has no implementation for --env %ENV% yet. 1>&2
echo Add real deploy steps here (or add deploy-to-%ENV%.bat), then re-run acpd. 1>&2
exit /b 0
EOF
  git add deploy.bat
  echo "NOTE: this project has no deploy.bat — created a placeholder/dispatcher and staged it." >&2
fi

if [ ! -f deploy.ps1 ]; then
  cat > deploy.ps1 <<'EOF'
# Auto-generated by the acpd skill -- generic deploy entry point for this
# project. Dispatches to a legacy ./deploy-to-<env>.ps1 if this project
# already has one; otherwise this is a TODO stub. Replace with real deploy
# steps.
param(
    [string]$Env = "dev"
)

$legacy = ".\deploy-to-$Env.ps1"
if (Test-Path $legacy) {
    & $legacy
    exit $LASTEXITCODE
}

Write-Warning "TODO: this project's deploy.ps1 has no implementation for --env $Env yet."
Write-Warning "Add real deploy steps here (or add $legacy), then re-run acpd."
exit 0
EOF
  git add deploy.ps1
  echo "NOTE: this project has no deploy.ps1 — created a placeholder/dispatcher and staged it." >&2
fi

# 4. Stage the rest of the already-tracked changes (never untracked files).
git add -u

# 5. Commit code + archiving as ONE commit.
COMMIT_MSG="issue-${ISSUE_NUM}: ${SUMMARY}

Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>"
git commit -m "$COMMIT_MSG"

# 6. Push.
git push

# 7. Deploy — dev only, ever. Calls the TARGET REPO's own deploy.sh (see
# step 3), not this script.
./deploy.sh --env dev

echo "✓ acpd complete: issue-${ISSUE_NUM} archived to ${ARCHIVE_DIR}/, committed, pushed, this project's deploy.sh --env dev run."
