@echo off
setlocal
rem Auto-generated by the acpd skill -- generic deploy entry point for this
rem project. Dispatches to a legacy deploy-to-<env>.bat if this project
rem already has one; otherwise this is a TODO stub. Replace with real
rem deploy steps.
set ENV=dev

:parse
if "%~1"=="" goto after
if /I "%~1"=="--env" (
    set ENV=%~2
    shift
    shift
    goto parse
)
shift
goto parse
:after

if exist "deploy-to-%ENV%.bat" (
    call "deploy-to-%ENV%.bat"
    exit /b %ERRORLEVEL%
)

echo TODO: this project's deploy.bat has no implementation for --env %ENV% yet. 1>&2
echo Add real deploy steps here (or add deploy-to-%ENV%.bat), then re-run acpd. 1>&2
exit /b 0
