# Auto-generated by the acpd skill -- generic deploy entry point for this
# project. Dispatches to a legacy ./deploy-to-<env>.ps1 if this project
# already has one; otherwise this is a TODO stub. Replace with real deploy
# steps.
param(
    [string]$Env = "dev"
)

$legacy = ".\deploy-to-$Env.ps1"
if (Test-Path $legacy) {
    & $legacy
    exit $LASTEXITCODE
}

Write-Warning "TODO: this project's deploy.ps1 has no implementation for --env $Env yet."
Write-Warning "Add real deploy steps here (or add $legacy), then re-run acpd."
exit 0
