#!/usr/bin/env bash
# Auto-generated by the acpd skill — generic deploy entry point for this
# project. Dispatches to a legacy ./deploy-to-<env>.sh if this project
# already has one; otherwise this is a TODO stub. Replace with real deploy
# steps. (Not to be confused with acpd's own deploy.sh, which is what
# generated this file.)
set -euo pipefail

ENV="dev"
while [ $# -gt 0 ]; do
  case "$1" in
    --env) ENV="$2"; shift 2 ;;
    *) shift ;;
  esac
done

LEGACY="./deploy-to-${ENV}.sh"
if [ -x "$LEGACY" ]; then
  exec "$LEGACY"
fi

echo "TODO: this project's deploy.sh has no implementation for --env $ENV yet." >&2
echo "Add real deploy steps here (or add $LEGACY), then re-run acpd." >&2
exit 0
